In [2]:
import torch

In [3]:
# Create random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, channels

shape = random_image_size_tensor.shape
dimension = random_image_size_tensor.ndim

print(f"Shape: {shape}")
print(f"Dimension: {dimension}")

Shape: torch.Size([224, 224, 3])
Dimension: 3


In [4]:
# Creating a tensors with all Zeros

zeroTensor = torch.zeros(size=(3, 4))
print(zeroTensor)

# Createing a tensor with all Ones

oneTensor = torch.ones(3, 4)
print(oneTensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
# Tensor within a range

tensorRange = torch.arange(start=1, end=100, step=10)
tensorRange

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [6]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,       # Data type of tensor 
                               device=None,      # CPU or GPU(CUDA)
                               requires_grad=False) # Track or not gradient with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [7]:
# Float 64 tensor

float_64_tensor = torch.tensor([2.0, 4.0, 6.0, 8.0],
                               dtype=torch.float64,
                               device=None,
                               requires_grad=False)
float_64_tensor

tensor([2., 4., 6., 8.], dtype=torch.float64)

In [8]:
# Change data type of a tensor

float_16_tensor = float_64_tensor.type(torch.float16)
float_16_tensor

tensor([2., 4., 6., 8.], dtype=torch.float16)

In [9]:
# Transpose of a tensor

random_tensor = torch.tensor([[1, 2],
                              [3, 4],
                              [5, 6]])

print(random_tensor)  # Original tensor
random_tensor.T       # Transpose tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[1, 3, 5],
        [2, 4, 6]])

*****Tensor Aggregation*****

In [10]:
# Create a Tensor

x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [11]:
# Min finding

torch.min(x), x.min()

(tensor(1), tensor(1))

In [12]:
# Max finding

torch.max(x), x.max()

(tensor(91), tensor(91))

In [13]:
# Mean finding - torch.mean() function requires a tensor lf float32 datatype to work --> INT datatype cannot be divided with floating point values

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [14]:
# Sum finding

torch.sum(x), x.sum()

(tensor(460), tensor(460))

Finding the positional MIN and MAX  ---> Index value of MIN and MAX

In [15]:
# Positional MIN

torch.argmin(x)

tensor(0)

In [16]:
# Positional MAX

torch.argmax(x)

tensor(9)

## Reshaping, Stacking, Squeezing and Unsqueezing tensors

* **Reshaping** - Reshapes an input tensor to a defined shape.
* **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* **Stacking** - Combine multiple tensors on top of each other(vstack) or side by side(hstack). 
* **Squeeze** - Removes the dimension of size 1 at the specified position (or all dimensions of size 1 if no position is specified).
* **Unsqueeze** - Adds a dimension of size 1 at the specified position.
* **Permute** - Return a view of the input with dimensions permuted(swapped) in a certain way.

In [17]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [18]:
# Reshape the tensor

x.reshape(2, -1)

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])

In [19]:
# View the tensor

x.view(2, -1)

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])

In [20]:
# Stack tensors Vertically

vertical_stack = torch.stack([x, x, x, x], dim=0)
vertical_stack

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [21]:
# Stack tensors Horizontally

horizontal_stack = torch.stack([x, x, x, x], dim=1)
horizontal_stack

tensor([[ 1,  1,  1,  1],
        [11, 11, 11, 11],
        [21, 21, 21, 21],
        [31, 31, 31, 31],
        [41, 41, 41, 41],
        [51, 51, 51, 51],
        [61, 61, 61, 61],
        [71, 71, 71, 71],
        [81, 81, 81, 81],
        [91, 91, 91, 91]])

In [ ]:
# Unsqueeze tensor
list = x.unsqueeze(0)   # Add a dimesion at 0 dimension
list.shape

torch.Size([1, 10])

In [23]:
# Permute the tensor

x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

x_permuted = x_original.permute(2, 0, 1)

print(f"Original tensor: {x_original.shape}")
print(f"Permuted tensor: {x_permuted.shape}")

Original tensor: torch.Size([224, 224, 3])
Permuted tensor: torch.Size([3, 224, 224])


## NumPy to Tensors

** Warning: Focus on the data type when converting from each other

In [24]:
import numpy as np

# NumPy array to Tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

print(f"NumPy: {array}")
print(f"Tensor: {tensor}")

NumPy: [1. 2. 3. 4. 5. 6. 7.]
Tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [25]:
# Tensor to NumPy

ones_tensor = torch.ones(10)
numpy_array = ones_tensor.numpy()

print(f"Tensor: {ones_tensor}")
print(f"NumPy: {numpy_array}")

Tensor: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
NumPy: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Reproducibility  -->  Random-Seed (Most commonly used 42)

In [26]:
# Making random but reproducible tensors

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
